### ISSUE TITLE
crypto_stream_aes128ctr has been removed

### ISSUE THREAD

**Issue by jedisct1** [alexpmorris/libsodium-delphi#3]
Hi!

Just a heads up: `crypto_stream_aes128ctr` had been deprecated for a long time, was not compiled in minimal builds, was not documented, and has been removed in the current dev code.

So, you may want to delete any references to it.

Cheers,

-Frank.

**Comment by alexpmorris** [comment]
thanks for the heads up @jedisct1!  I removed the deprecated references, though I did leave in the 3 that were not marked as deprecated:

```
crypto_stream_aes128ctr_keybytes
crypto_stream_aes128ctr_noncebytes
crypto_stream_aes128ctr_beforenmbytes
```

**Comment by jedisct1** [comment]
You can remove them all :)

The reason these constants were not marked as deprecated is that they were used internally. This is not the case any more, and they are gone with their friends :)

On the other hand, 1.0.14 introduced a nice `crypto_secretstream()` API that might be good to have :)

**Comment by alexpmorris** [comment]
I removed the rest of the aes123ctr functions, and added the crypto_secretstream() functions as well!

**Comment by rrr9rrr** [comment]
[jedisct1](https://github.com/jedisct1)
opened [on Sep 29, 2017](https://github.com/alexpmorris/libsodium-delphi/issues/3#issue-261760659)
@jedisct1, WHY you had remove crypto_stream_aes128ctr_* from libsodium?!
CPAN modules Crypt::NaCl::Sodium and Alien::Sodium are failing to build without it!

Error log:

 sudo cpan Crypt::NaCl::Sodium::stream
Reading '/home/root/.cpan/Metadata'
  Database was generated on Thu, 25 Dec 2025 17:17:01 GMT
Running install for module 'Crypt::NaCl::Sodium::stream'
Checksum for /home/root/.cpan/sources/authors/id/A/AJ/AJGB/Crypt-NaCl-Sodium-1.0.8.0.tar.gz ok
Configuring A/AJ/AJGB/Crypt-NaCl-Sodium-1.0.8.0.tar.gz with Makefile.PL
AES256GCM is not available
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Crypt::NaCl::Sodium
Writing MYMETA.yml and MYMETA.json
  AJGB/Crypt-NaCl-Sodium-1.0.8.0.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for A/AJ/AJGB/Crypt-NaCl-Sodium-1.0.8.0.tar.gz
cp lib/Crypt/NaCl/Sodium/sign.pod blib/lib/Crypt/NaCl/Sodium/sign.pod
cp lib/Crypt/NaCl/Sodium/shorthash.pod blib/lib/Crypt/NaCl/Sodium/shorthash.pod
cp lib/Crypt/NaCl/Sodium/generichash.pod blib/lib/Crypt/NaCl/Sodium/generichash.pod
cp lib/Crypt/NaCl/Sodium/onetimeauth.pod blib/lib/Crypt/NaCl/Sodium/onetimeauth.pod
cp lib/Crypt/NaCl/Sodium/pwhash.pod blib/lib/Crypt/NaCl/Sodium/pwhash.pod
cp lib/Data/BytesLocker.pod blib/lib/Data/BytesLocker.pod
cp lib/Crypt/NaCl/Sodium/box.pod blib/lib/Crypt/NaCl/Sodium/box.pod
cp lib/Crypt/NaCl/Sodium/hash.pod blib/lib/Crypt/NaCl/Sodium/hash.pod
cp lib/Crypt/NaCl/Sodium/aead.pod blib/lib/Crypt/NaCl/Sodium/aead.pod
cp lib/Crypt/NaCl/Sodium.pm blib/lib/Crypt/NaCl/Sodium.pm
cp lib/Crypt/NaCl/Sodium/scalarmult.pod blib/lib/Crypt/NaCl/Sodium/scalarmult.pod
cp lib/Crypt/NaCl/Sodium/secretbox.pod blib/lib/Crypt/NaCl/Sodium/secretbox.pod
cp lib/Crypt/NaCl/Sodium/auth.pod blib/lib/Crypt/NaCl/Sodium/auth.pod
cp lib/Crypt/NaCl/Sodium/stream.pod blib/lib/Crypt/NaCl/Sodium/stream.pod
Running Mkbootstrap for Sodium ()
chmod 644 "Sodium.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Sodium.bs blib/arch/auto/Crypt/NaCl/Sodium/Sodium.bs 644
"/usr/bin/perl" "/usr/share/perl/5.36/ExtUtils/xsubpp"  -typemap '/usr/share/perl/5.36/ExtUtils/typemap' -typemap '/home/root/.cpan/build/Crypt-NaCl-Sodium-1.0.8.0-9/typemap'  Sodium.xs > Sodium.xsc
mv Sodium.xsc Sodium.c
aarch64-linux-gnu-gcc -c  -I. -I/usr/local/include  -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.0.8.0\" -DXS_VERSION=\"1.0.8.0\" -fPIC "-I/usr/lib/aarch64-linux-gnu/perl/5.36/CORE"   Sodium.c
Sodium.xs: In function ‘XS_Crypt__NaCl__Sodium__stream_AES128CTR_NONCEBYTES’:
Sodium.xs:4538:18: error: ‘crypto_stream_aes128ctr_NONCEBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa208_NONCEBYTES’?
 4538 |         RETVAL = crypto_stream_aes128ctr_NONCEBYTES;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  crypto_stream_salsa208_NONCEBYTES
Sodium.xs:4538:18: note: each undeclared identifier is reported only once for each function it appears in
Sodium.xs: In function ‘XS_Crypt__NaCl__Sodium__stream_AES128CTR_KEYBYTES’:
Sodium.xs:4545:18: error: ‘crypto_stream_aes128ctr_KEYBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa20_KEYBYTES’?
 4545 |         RETVAL = crypto_stream_aes128ctr_KEYBYTES;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  crypto_stream_salsa20_KEYBYTES
Sodium.xs: In function ‘XS_Crypt__NaCl__Sodium__stream_keygen’:
Sodium.xs:4573:28: error: ‘crypto_stream_aes128ctr_KEYBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa20_KEYBYTES’?
 4573 |                 key_size = crypto_stream_aes128ctr_KEYBYTES;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            crypto_stream_salsa20_KEYBYTES
Sodium.xs: In function ‘XS_Crypt__NaCl__Sodium__stream_nonce’:
Sodium.xs:4608:30: error: ‘crypto_stream_aes128ctr_NONCEBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa208_NONCEBYTES’?
 4608 |                 nonce_size = crypto_stream_aes128ctr_NONCEBYTES;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              crypto_stream_salsa208_NONCEBYTES
Sodium.xs: In function ‘XS_Crypt__NaCl__Sodium__stream_bytes’:
Sodium.xs:4690:30: error: ‘crypto_stream_aes128ctr_NONCEBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa208_NONCEBYTES’?
 4690 |                 nonce_size = crypto_stream_aes128ctr_NONCEBYTES;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              crypto_stream_salsa208_NONCEBYTES
Sodium.xs:4691:28: error: ‘crypto_stream_aes128ctr_KEYBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa20_KEYBYTES’?
 4691 |                 key_size = crypto_stream_aes128ctr_KEYBYTES;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            crypto_stream_salsa20_KEYBYTES
Sodium.xs:4692:35: error: ‘crypto_stream_aes128ctr’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa208_xor’?
 4692 |                 bytes_function = &crypto_stream_aes128ctr;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                                   crypto_stream_salsa208_xor
Sodium.xs:4702:17: warning: ‘crypto_stream_salsa208’ is deprecated [-Wdeprecated-declarations]
 4702 |                 bytes_function = &crypto_stream_salsa208;
      |                 ^~~~~~~~~~~~~~
In file included from /usr/local/include/sodium.h:65,
                 from Sodium.xs:11:
/usr/local/include/sodium/crypto_stream_salsa208.h:38:5: note: declared here
   38 | int crypto_stream_salsa208(unsigned char *c, unsigned long long clen,
      |     ^~~~~~~~~~~~~~~~~~~~~~
Sodium.xs: In function ‘XS_Crypt__NaCl__Sodium__stream_xor’:
Sodium.xs:4780:30: error: ‘crypto_stream_aes128ctr_NONCEBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa208_NONCEBYTES’?
 4780 |                 nonce_size = crypto_stream_aes128ctr_NONCEBYTES;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              crypto_stream_salsa208_NONCEBYTES
Sodium.xs:4781:28: error: ‘crypto_stream_aes128ctr_KEYBYTES’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa20_KEYBYTES’?
 4781 |                 key_size = crypto_stream_aes128ctr_KEYBYTES;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            crypto_stream_salsa20_KEYBYTES
Sodium.xs:4782:33: error: ‘crypto_stream_aes128ctr_xor’ undeclared (first use in this function); did you mean ‘crypto_stream_salsa208_xor’?
 4782 |                 xor_function = &crypto_stream_aes128ctr_xor;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 crypto_stream_salsa208_xor
Sodium.xs:4792:17: warning: ‘crypto_stream_salsa208_xor’ is deprecated [-Wdeprecated-declarations]
 4792 |                 xor_function = &crypto_stream_salsa208_xor;
      |                 ^~~~~~~~~~~~
/usr/local/include/sodium/crypto_stream_salsa208.h:43:5: note: declared here
   43 | int crypto_stream_salsa208_xor(unsigned char *c, const unsigned char *m,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:369: Sodium.o] Ошибка 1
  AJGB/Crypt-NaCl-Sodium-1.0.8.0.tar.gz
  /usr/bin/make -- NOT OK
