### ISSUE TITLE
How to use this when I build android app with Delphi

### ISSUE THREAD

**Issue by 3874** [alexpmorris/libsodium-delphi#5]
Dear, Alex

Thanks to you, I am building my app so well. 
However, I faced some huddle when I compile this as android app.
Please let me know how to do it.
Your lisodium.pas file can't be compiled for mobile app.
I think that you have a great solution. Please help me.

Best regards,
Francis

**Comment by alexpmorris** [comment]
this libsodium wrapper is for the windows DLL, which would not be compatible with libsodium on other OSes such as Android.  However, there are a bunch of libsodium wrappers for java / Android, so you should be able to adapt one of those to work with your project.

https://github.com/terl/lazysodium-android

http://docwiki.embarcadero.com/RADStudio/Rio/en/Adding_A_Java_Library_to_Your_Application_Using_the_Project_Manager

<img src="http://docwiki.embarcadero.com/images/RADStudio/Rio/e/a/a2/ProjectManagerAndroidLibrariesAdd.png">
